module.exports = {
    INSERT_RECORD: "insertRecord",
    UPDATE_RECORD: "updateRecord",
    GET_RECORD: "getRecord",
    DELETE_RECORD: "deleteRecord",
    FILTER_RECORDS: "filter",
    GET_ALL_RECORDS: "getAllRecords",
    BEGIN_BATCH: "beginBatch",
    COMMIT_BATCH: "commitBatch",
    CANCEL_BATCH: "cancelBatch",
    READ_KEY: "readKey",
    WRITE_KEY: "writeKey",
    ADD_IN_QUEUE: "addInQueue",
    QUEUE_SIZE: "queueSize",
    LIST_QUEUE: "listQueue",
    GET_OBJECT_FROM_QUEUE: "getObjectFromQueue",
    DELETE_OBJECT_FROM_QUEUE: "deleteObjectFromQueue",
    STORE_SEED_SSI: "storeSeedSSI",
    SIGN_FOR_KEY_SSI: "signForKeySSI",
    STORE_DID: "storeDID",
    ADD_PRIVATE_KEY_FOR_DID: "addPrivateKeyForDID",
    SIGN_FOR_DID: "signForDID",
    VERIFY_FOR_DID: "verifyForDID",
    ENCRYPT_MESSAGE: "encryptMessage",
    DECRYPT_MESSAGE: "decryptMessage",
    GET_PRIVATE_INFO_FOR_DID:"getPrivateInfoForDID"
}